### ISSUE TITLE
Any nuget package?

### ISSUE THREAD

**Issue by PieroCastillo** [jp2masa/Avalonia.Flexbox#1]
Hello, I'd wanna build an application with this project, but there isn't some nuget package, when you release any package?

**Comment by jp2masa** [comment]
Done! Here is 0.1.0: https://www.nuget.org/packages/jp2masa.Avalonia.Flexbox/.

I can't say it's really stable, so if you find bugs please report them.

**Comment by PieroCastillo** [comment]
thanks u! I need the flexbox long ago! now I can some projects with this.
